spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/adminDB
spring.datasource.username=shilpi
spring.datasource.password=shilpi
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.show-sql=true

spring.cloud.stream.kafka.binder.brokers=localhost:9092

spring.cloud.function.definition=approvalRequestConsumer;sellerApprovalRequestConsumer
spring.cloud.stream.bindings.approvalRequestConsumer-in-0.destination=approval-request-topic
spring.cloud.stream.bindings.approvalRequestConsumer-in-0.content-type=application/json


#pulling from Kafka for seller registration
spring.cloud.stream.bindings.sellerApprovalRequestConsumer-in-0.destination=seller-approval-request-topic
spring.cloud.stream.bindings.sellerApprovalRequestConsumer-in-0.content-type=application/json

#pushing to Kafka after seller registration
spring.cloud.stream.bindings.seller-register-response-out-0.destination=seller-register-response-topic
spring.cloud.stream.bindings.seller-register-response-out-0.content-type=application/json

