#server.port=9002
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=28017
#spring.data.mongodb.uri=mongodb://user:pass@localhost:28017/catalogDB?authSource=admin

server.port=9002
spring.data.mongodb.host=localhost
spring.data.mongodb.port=28017
spring.data.mongodb.uri=mongodb://user:pass@localhost:28017/catalogDB?authSource=admin
spring.mongodb.uri=mongodb://user:pass@localhost:28017/catalogDB?authSource=admin
