spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/sellerDB
spring.datasource.username=shilpi
spring.datasource.password=shilpi
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db


spring.cloud.stream.kafka.binder.brokers=localhost:9092

#pushing request to Kafka for seller registration
spring.cloud.stream.bindings.seller-approvalRequest-out-0.destination=seller-approval-request-topic
spring.cloud.stream.bindings.seller-approvalRequest-out-0.content-type=application/json

#pulling request from Kafka after approver registered seller
spring.cloud.function.definition=sellerRegistrationConsumer
spring.cloud.stream.bindings.sellerRegistrationConsumer-in-0.destination=seller-register-response-topic
spring.cloud.stream.bindings.sellerRegistrationConsumer-in-0.content-type=application/json

#pushing request to Kafka after seller is registered , email to send on sellerMail
spring.cloud.stream.bindings.seller-registrationDecision-out-0.destination=seller-registrationDecision-topic
spring.cloud.stream.bindings.seller-registrationDecision-out-0.content-type=application/json

#pushing request to Kafka after seller is deactivated/activated/suspended , email to send on sellerMail
spring.cloud.stream.bindings.seller-status-out-0.destination=seller-status-topic
spring.cloud.stream.bindings.seller-status-out-0.content-type=application/json



